
import Head from "next/head";
import Header from "./components/Header"
import Footer from "./components/Footer";
import styles from "../styles/home.module.css"
import Image from "next/image";


export default function Home() {
    return ( 
        <div>

        <Head>
            <title>This is a Next js App</title>
            <meta name="description"  content="Generated by create next app"/>
            {/* <link rel="stylesheet" href="/omm" /> */}
        </Head>


            
            <section className="intro-section">
                <div className="img-container">
                        <Image 
                        src="/community.png" 
                        height={600}
                        width={900}
                        className="home-image"
                        />
                </div>
                
                <div className="content">
                    <div className="heading">
                    Open Source Community Africa {'{'} <span className="kampala-home">Kampala</span>{" }"}
                    </div>
                    <div className="descr">
                    Open Source Community Africa (OSCA) is a community for open source lovers, enthusiasts, advocates and experts within and across Africa, with the sole aim of increasing th e rate of credible open source contributions by Africans.
                </div>

                <div className={styles.test}>
                    thiis is a test div
                </div>
        </div>
            </section>
            
        </div>
     );
}

